# Numpy 
 - It is python library that is standard for working with numerical data in python.
 - the numpy library contains multidimensional array and matrix data structures.
 - Numpy stands for numerical python

## Installation of numpy
 
 - pip install numpy

## Importing  numpy
 -it is imported as 
    ----import numpy as np 

## example
 -----a=np.arange(5)
 -----a2=a[np.newaxis,:]
 -----a2.shape

# ARRAY
 - An array is a grid of values and it contains information about raw data ,how to locate an element and how to interpret an element 

# Numpy practice

In [1]:
#import library in j.notebook
import numpy as np

# Creating an array using numpy

# 1-D array

In [49]:
import numpy as np
food = np.array(["Pakora","Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
number=np.array([5,6,7])
number

array([5, 6, 7])

In [5]:
figure=np.array(["g","h","q"])
figure

array(['g', 'h', 'q'], dtype='<U1')

In [6]:
food=(["briyani","raita","karahi"])
food

['briyani', 'raita', 'karahi']

In [7]:
len(food)

3

In [8]:
number=([3,5,8,9,0])
number

[3, 5, 8, 9, 0]

### zeros

In [9]:
import numpy as np
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

## arange

In [17]:
import numpy as np 
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Specific Interval

In [18]:
np.arange(2,30,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [20]:
np.arange(3,40,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [25]:
np.arange(4,10,4)

array([4, 8])

### Table

In [27]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
np.arange(159,1590,159)

array([ 159,  318,  477,  636,  795,  954, 1113, 1272, 1431])

### Array fuctions

In [35]:
a=np.array([2,4,10,63,50,40,33])
a

array([ 2,  4, 10, 63, 50, 40, 33])

### sort
 - np.sort()

In [37]:
a.sort()
a

array([ 2,  4, 10, 33, 40, 50, 63])

In [40]:
b=np.array([30,50,6,6,7,3,2,8])
b

array([30, 50,  6,  6,  7,  3,  2,  8])

In [41]:
b.sort()
b

array([ 2,  3,  6,  6,  7,  8, 30, 50])

### concatinate
 - np.concatenate()

In [46]:
c=np.concatenate((a,b))
c

array([ 2,  4, 10, 33, 40, 50, 63,  2,  3,  6,  6,  7,  8, 30, 50])

In [48]:
c.sort()
c

array([ 2,  2,  3,  4,  6,  6,  7,  8, 10, 30, 33, 40, 50, 50, 63])

# 2-D arrays

In [54]:
a=np.array([[1,2,3,4],[5,6,7,8]])

a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
b=np.array([[2,3,4],[7,8,9]])
b

array([[2, 3, 4],
       [7, 8, 9]])

### concatinating 2-D arrays

In [59]:
c=np.concatenate((a,b),axis=1)
c

array([[1, 2, 3, 4, 2, 3, 4],
       [5, 6, 7, 8, 7, 8, 9]])

### to find dimension of array

In [65]:
a.ndim

2

In [66]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
d.ndim

2

### size of array

In [68]:
d.size

9

### shape of array

In [73]:
d.shape

(3, 3)

#### - means 3 rows and 3 columns in dimension d

### Reshaping array

In [85]:
c=np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
e=c.reshape(5,2)
e

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [87]:
f=np.arange(16)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [92]:
g=f.reshape(2,8)
g

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [89]:
h=np.arange(6)
h

array([0, 1, 2, 3, 4, 5])

In [93]:
i=h.reshape(3,2)
i

array([[0, 1],
       [2, 3],
       [4, 5]])

## Converting 1-D array to 2 -D array

In [96]:
x=np.array([3,4,6,8,9,0,1,7])
x


array([3, 4, 6, 8, 9, 0, 1, 7])

In [97]:
x.ndim

1

In [98]:
x.shape

(8,)

### COLUMN WISE 2-D CONVERSION

In [101]:
y=x[np.newaxis,:]
y

array([[3, 4, 6, 8, 9, 0, 1, 7]])

### ROW WISE 2-D  CONVERSION

In [102]:
y=x[:,np.newaxis]
y

array([[3],
       [4],
       [6],
       [8],
       [9],
       [0],
       [1],
       [7]])

In [104]:
z=np.arange(10) 
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
s=z[:,np.newaxis]
s

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [108]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### multiplication and addition

In [109]:
a*6

array([[ 6, 12, 18, 24],
       [30, 36, 42, 48]])

In [110]:
a.sum()

36

### Reversing of an array
 - np.flip()

In [118]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
x2=np.flip(z)
x2

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])